2018-11-15 16:06:36,244 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
2018-11-15 16:06:56,091 ERROR: Exception on /edit_profile [POST] [in /home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/kaori/Desktop/flasky/app/routes.py", line 83, in edit_profile
    db.session.commit()
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2381, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2345, in _flush
    flush_context.execute()
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 395, in execute
    rec.execute(self)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 560, in execute
    uow
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 768, in _emit_update_statements
    execute(statement, multiparams)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username [SQL: 'UPDATE user SET username=?, about_me=? WHERE user.id = ?'] [parameters: ('yzx', 'The best kaori', 1)] (Background on this error at: http://sqlalche.me/e/gkpj)
2018-11-15 18:04:54,482 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
2018-11-15 18:23:51,447 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
2018-11-19 09:38:44,724 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
2018-11-22 11:35:07,747 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
2018-11-27 10:58:11,063 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
2018-11-27 18:11:26,110 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
2018-11-27 18:11:44,408 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
2018-11-27 19:14:54,060 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
2018-11-27 23:44:26,029 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
2018-11-27 23:44:31,868 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
2018-11-27 23:53:20,559 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
2018-11-27 23:59:13,743 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
2018-11-28 00:05:57,395 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
2018-11-28 00:11:10,702 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
2018-11-29 10:34:48,137 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
2018-11-29 11:02:51,520 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
2018-11-29 12:27:45,873 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
2018-11-29 12:28:25,128 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
2018-11-29 12:29:48,130 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
2018-11-29 12:32:00,635 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:48]
